remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

title: "Ontogen"
description: >-
  A data-control-management system for RDF datasets
url: "https://ontogen.io"
baseurl: ""
name: "Marcel Otto"
email: marcelotto@gmx.de
title_separator: "|"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ontogen"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://mastodon.social/@marcelotto"
    - label: "X"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/marcelotto"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
