remote_theme: mmistakes/minimal-mistakes

minimal_mistakes_skin: "default"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

title: "Ontogen"
title_separator: "|"
description: >-
  "A Version Control System for RDF datasets"
logo: "/assets/images/ontogen-logo.png"
url: "https://ontogen.io"
baseurl: ""
name: "Marcel Otto"
email: marcelotto@gmx.de
copyright: "Marcel Otto"
copyright_url: "http://marcelotto.net"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      toc: true
      read_time: true
      comments: true
      share: true
      related: true

enable_copy_code_button: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ontogen"
      target: _blank
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://mastodon.social/@marcelotto"
      target: _blank
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/marcel-otto-a68245b8/"
      target: _blank

author:
  name: "Marcel Otto"
  avatar: "/assets/images/mo-profile.jpeg"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/marcelotto"
      target: _blank
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://mastodon.social/@marcelotto"
      target: _blank
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/marcel-otto-a68245b8/"
      target: _blank

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
